project:
  name: '@project.artifactId@'
  version: '@project.version@'
  description: '@project.description@'
info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: '@project.description@'
    version: '@project.version@'



#spring.banner.charset=UTF-8
#spring.banner.location=classpath:banner.txt

spring:
  output:
    ansi:
      enabled: ${SPRING_OUTPUT_ANSI_ENABLE}
  banner:
    charset: ${SPRING_BANNER_CHARSET}
    location: ${SPRING_BANNER_LOCATION}
  jpa:
    open-in-view: false



#Logging
logging:
  level:
    br.com.senaigo: debug
    org.springframework.web: info

resource:
  pessoa-post: Método responsável por criar uma nova pessoa.
  pessoa-put: Método responsável por atualizar todo os dados de uma pessoa.
  pessoa-patch: Método responsável por atualizar parte de um objeto pessoa.
  pessoa-delete: Método responsável por deletetar o registro pessoa.
  pessoa-delete-by-id: Método responsável por deletar um registro por identificador.
